<?php

/**
 * PluginDmTickerTapeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmTickerTapeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmTickerTapeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmTickerTape');
    }
}